server:
  port: 9002
spring:
  application:
    name: cloudalibaba-could-payment
  cloud:
    nacos:
      discovery:
        server-addr: 10.48.125.117:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'
