server:
  port: 84
spring:
  application:
    name: comsumer-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848       #nacos地址
            dataId: comsumer-sentinel-service
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
#openfeign 对sentinel的支持
service-url:
  nacos-user-service: http://cloudalibaba-sentinel-payment
feign:
  sentinel:
    enabled: true